### ISSUE TITLE
Feature: Import from Excel2sqlite

### ISSUE THREAD

**Issue by Scrounger** [androidmads/SQLite2XL#1]
@androidmads 
Thanks for this great lib!
Can you also implement the function to import Excel files to the sqlite database, all or single tables?

**Comment by Harti** [comment]
That would be super awesome indeed. +1

**Comment by Harti** [comment]
I got this quick&dirty solution working for me, feel free to use and adapt it to your needs: 
https://gist.github.com/Harti/ffefe1bb4d84d2a0602849d43a8bd025

**Comment by androidmads** [comment]
Check my Repo. I have Added the functionality to import Excel into SQLite
