### ISSUE TITLE
Cannot resolve symbol 'SqliteToExcel'

### ISSUE THREAD

**Issue by ajinkya5130** [androidmads/SQLite2XL#12]
Not able to resolve this error 
I have added dependency in build.gradle

**Comment by androidmads** [comment]
WHAT IS YOUR ERROR

**Comment by ajinkya5130** [comment]
declaration error ...
If i am defining for first time ,i.e on Oncreate Method.
Sqlite2xl sqlite = new Sqlite2Xl();(Whatever basic declaration to access
that library..)


Regards,
Ajinkya Kalaskar
+91 9011320039

**Comment by ChandelaDeveloper** [comment]
Hello I got same error in my implementation

**Comment by ChandelaDeveloper** [comment]
Can you please help me out of this

**Comment by ChandelaDeveloper** [comment]
Just make 
SQLiteToExcel sqliteToExcel = new SQLiteToExcel(...)

**Comment by ajinkya5130** [comment]
I wrote same as u said in previous mail... But it's not working

**Comment by ChandelaDeveloper** [comment]
Can you please share your code with me?
Actually  the same code working for me
