### ISSUE TITLE
SQLiteException: table sqlite_sequence may not drop - Import excel to sqlite datebase 

### ISSUE THREAD

**Issue by kamalbunkar** [androidmads/SQLite2XL#13]
### Expected behavior 
I am trying to import excel sheet that I export using the method given on your project. The export method is working fine. When I am trying to import excel sheet to sqlite database It must get all the rows to sqlite tables. but is didn't.

### Actual behavior
 it is showing a table sqlite_sequence may not drop..(I have set true on droptable ). 
android.database.sqlite.SQLiteException: table sqlite_sequence may not be dropped (code 1): , while compiling: DROP TABLE IF EXISTS sqlite_sequence

If I make it false then It is showing runtime exceptions.
E/SQLiteLog: (1) object name reserved for internal use: sqlite_sequence
android.database.sqlite.SQLiteException: object name reserved for internal use: sqlite_sequence (code 1): , while compiling: CREATE TABLE IF NOT EXISTS sqlite_sequence(name TEXT,seq TEXT)

### Steps to reproduce the issue
try in import excel sheet which have multiple sheets.

**Comment by androidmads** [comment]
I have tried the same and this issue is not produced. So, I have closed this issue. You can open if this issue is produced. I will support ASAP.
