### ISSUE TITLE
How to find the data in excel which is imported from sqlite

### ISSUE THREAD

**Issue by s1reshu** [androidmads/SQLite2XL#15]
### Actual behavior

I tried your code sir. But I dont know whether it is getting saved. Can you please tell where the database is exported

**Comment by androidmads** [comment]
SQLiteToExcel sqliteToExcel = new SQLiteToExcel(getApplicationContext(), DB_NAME, **directory_path**);

You can find the excel sheet in your specified path while exporting the Excel file
