### ISSUE TITLE
Cannot resolve symbol 'SqliteToExcel'

### ISSUE THREAD

**Issue by ajinkya5130** [androidmads/SQLite2XL#16]
compile 'com.ajts.androidmads.SQLite2Excel:library:1.0.3'
is showing problem in build.gradle (Failed to resolve: com.ajts.androidmads.SQLite2Excel:library:1.0.3)

so i changed from compile 'com.ajts.androidmads.SQLite2Excel:library:1.0.3' to compile 'com.ajts.androidmads.SQLite2Excel:library:1.0.2'

after that it shows Cannot resolve symbol 'SqliteToExcel' in OnCreate method

**Comment by androidmads** [comment]
Fixed this issue
