### ISSUE TITLE
need 1.0.3 version in jitpack

### ISSUE THREAD

**Issue by rkarimi88** [androidmads/SQLite2XL#17]
Hi
I am interested in your library and gonna use it in my app (Really Thanks), but my problem is that i cannot use the newest version (1.0.3).

I can't add them to Android Studio directly, so i used [jitpack.io](https://jitpack.io/#androidmads/SQLite2XL) to change the link..... but it has 1.0.2 version....

Would you please do me a favor and upgrade your library in a way that jitpack.io can see it?

Thanks in advance.

**Comment by androidmads** [comment]
Try version 1.0.4.
