### ISSUE TITLE
I cant import your library

### ISSUE THREAD

**Issue by JuanIri1999** [androidmads/SQLite2XL#18]
Hi, sorry for my english.. i try to put your library in android studio but i cant: Android studio show me this:

Failed to resolve: com.ajts.androidmads.SQLite2Excel:library:1.0.4

Can you solve this? Also, i try with 1.0.3 and 1.0.2 but show me the same error.

**Comment by tarunkonda123** [comment]
try this 
app level     implementation 'com.ajts.androidmads.SQLite2Excel:library:1.0.0'
project level classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.2'
        classpath 'com.github.dcendents:android-maven-gradle-plugin:1.4.1'

**Comment by androidmads** [comment]
Hi Devs, 
I have checked this issue. But the library imports perfectly. Do share your app/project level gradle code

**Comment by androidmads** [comment]
Import the following 

`
implementation 'com.ajts.androidmads.SQLite2Excel:library:1.0.4'
`

**Comment by tirumalarajajee** [comment]
Hi ,
     Same is the issue with my project, though syncing gradle but with no downloads of the class and project  does'nt implement the class SQLiteToExcel, i even added  classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.2'
classpath 'com.github.dcendents:android-maven-gradle-plugin:1.4.1' in project level, Kindly help

**Comment by jesulo** [comment]
> Hi , Same is the issue with my project, though syncing gradle but with no downloads of the class and project does'nt implement the class SQLiteToExcel, i even added classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.2' classpath 'com.github.dcendents:android-maven-gradle-plugin:1.4.1' in project level, Kindly help
Do yo solve it? regards

**Comment by rrahul-kamble3** [comment]
1. Visit this link https://github.com/androidmads/SQLite2XL/tree/master/library/src/main/java/com/ajts/androidmads/library
2. Copy [ExcelToSQLite.java](https://github.com/androidmads/SQLite2XL/blob/master/library/src/main/java/com/ajts/androidmads/library/ExcelToSQLite.java) & [SQLiteToExcel.java](https://github.com/androidmads/SQLite2XL/blob/master/library/src/main/java/com/ajts/androidmads/library/SQLiteToExcel.java) these two classes, to your local project.
3. Replace com.ajts.androidmads.SQLite2Excel:library:1.0.* this with implementation 'org.apache.poi:poi:3.16' in app level build.gradle
4. Remove imports related to com.ajts.androidmads.SQLite2Excel dependency from your entire project and add newly added above two classes imports over there
5. Sync the project and run. 
6. That's it!

**Comment by androidmads** [comment]
Hi [tirumalarajajee](https://github.com/tirumalarajajee) and [jesulo](https://github.com/jesulo), 

Until your issues are resolved, you can download the project from GitHub and add it as a module to your project. This way, you can meet the requirements without making code changes and upgrade to the newer version later once the library sync issue is resolved.
