### ISSUE TITLE
Import problem

### ISSUE THREAD

**Issue by mohammadso** [androidmads/SQLite2XL#4]
when i export dataBase to excel it woks fine
and when i try to import the exported file it works fine two,
but when i add new data to exported file in desktop excel and try to import edited file
it just imports the columns that has been created by itself not my new columns
please help....
what should I do in desktop excel?

**Comment by androidmads** [comment]
Hey Bro,

I have Added this support in my library and i have closed the issue. If you have any difficulties or issue, you can reopen the issue.
