### ISSUE TITLE
App Missing Files 

### ISSUE THREAD

**Issue by rayliverified** [androidmads/SQLite2XL#5]
The sample app does not build correctly because it is missing some files. 
List of missing files:
*activity_xl_2_sqlite.xml
*list_item.xml
*menu_main.xml

Where are these critical files? I do not see them in any previous commits.

**Comment by androidmads** [comment]
Hi Ray Li,

These files are used with sample app. This is not an issue. You can add your own layout files to run this library. I will update ASAP.

**Comment by rayliverified** [comment]
Yes, I understand they only affect the sample app. However, xls importing is failing for me so I want to test and try to troubleshoot the issue.

**Comment by androidmads** [comment]
Let me know if you find the solution or difficulties
