### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by mahdi312** [androidmads/SQLite2XL#6]
Hi, I wanna use your library for my app to create an excel file from my database , but I can't. I can add library to dependencies in gradle and no more. how is your function for using it?  and how can i use it?
I will be appreciate you to help me... I'm a beginner in android.

**Comment by androidmads** [comment]
Hi,

You can add and use this library mentioned in [Readme](https://github.com/androidmads/SQLite2XL/blob/master/README.md) or [Wiki](https://github.com/androidmads/SQLite2XL/wiki/SQLite2XL-v1.0.2)

**Comment by paitsystems** [comment]
There is limit of rows in xls file. How to overcome this by using xlsx file?

**Comment by androidmads** [comment]
You can change your file's extensions from **".xls"** to **".xlsx"**
