### ISSUE TITLE
Unable to generate signed APK when proguard is enabled

### ISSUE THREAD

**Issue by zfc0812** [androidmads/SQLite2XL#8]
Thanks for this great SQlite2XL library. However, this library is causing signed APK unable to be generated when proguard is enable. Here are some lines of warning:

```
Warning:org.apache.poi.hssf.usermodel.DummyGraphics2d: can't find superclass or interface java.awt.Graphics2D
Warning:org.apache.poi.hssf.usermodel.EscherGraphics: can't find superclass or interface java.awt.Graphics
Warning:org.apache.poi.hssf.usermodel.EscherGraphics2d: can't find superclass or interface java.awt.Graphics2D

```

I tried to add  `-keep class java.awt.** { *; }` to my proguard but this is still not working. How to solve this problem?

**Comment by androidmads** [comment]
Add the following code in proguard
`-keep public class org.apache.poi.** {*;}`
Let me know if you find any issues further

**Comment by zfc0812** [comment]
This is not working. I solved it by adding:
`-dontwarn org.apache.poi.**`

**Comment by androidmads** [comment]
Thanks bro.

**Comment by lokeshsunhare** [comment]
use this code in proguard-rule.pro
-dontwarn java.awt.**
