### ISSUE TITLE
Upload not successfull

### ISSUE THREAD

**Issue by syazskylex** [androidmads/SQLite2XL#9]
Hi to developer, 
I faced some problem. Well, it might be simple to you. To me it is liked almost complicated to me ...
I cannot upload from excel to sql. It keeps going error but it doesnt have error at "RUN" tab only blue and black text no red text.

"Please create excel file" keeps appearing . Anything else I should have ? {@private void XL2SQL()}
I have download and try to upload the excel using your app at google play store still no luck.
also do decompiler online to check the wrong still the same.

using 4.4 kitkat api 19;

private void SQL2XL(){
        String directory_path = Environment.getExternalStorageDirectory().getPath();
        SQLiteToExcel sqliteToExcel = new SQLiteToExcel(getApplicationContext(), DBHandler.DATABASE_NAME, directory_path);
        sqliteToExcel.exportAllTables("users.xls", new SQLiteToExcel.ExportListener() {
            @Override
            public void onStart() {Toast.makeText(home.this, "Exporting ...", Toast.LENGTH_LONG).show();}
            @Override
            public void onCompleted(String filePath) {Toast.makeText(home.this, "Successfully Exported", Toast.LENGTH_LONG).show();}
            @Override
            public void onError(Exception e) {Toast.makeText(home.this, "Please create database", Toast.LENGTH_LONG).show();}
        });
    }
    private void XL2SQL(){
        String directory_path = Environment.getExternalStorageDirectory().getPath() + "users.xls";
        ExcelToSQLite excelToSQLite = new ExcelToSQLite(getApplicationContext(), DBHandler.DATABASE_NAME, false);
        excelToSQLite.importFromFile(directory_path, new ExcelToSQLite.ImportListener() {
            @Override
            public void onStart() {Toast.makeText(home.this, "Importing ...", Toast.LENGTH_LONG).show();}

            @Override
            public void onCompleted(String dbName) {Toast.makeText(home.this, "Successfully Imported", Toast.LENGTH_LONG).show();}

            @Override
            public void onError(Exception e) {Toast.makeText(home.this, "Please create excel file", Toast.LENGTH_LONG).show();}
        });
    }

**Comment by syazskylex** [comment]
Export working fine.
Import is **"onError"** section . I think it needs additional file
Also testing different platform api not working upload excel to sql using official google play app.
Did I need to know how to uploading excel.
I did export(work) and reimport(not work) @same directory @extdir/backup/users.xls
using latest library 1.0.2
Thank you, great work (y)

**Comment by ArunkumarAndanshetti** [comment]
Export is working perfectly fine but try to import existing excel sheet getting error ....

Thank you help me

**Comment by syazskylex** [comment]
To user please use java poi to import the excel. I guarenteed It will be success. I have made it until work. Very thankfull to developer made my way easier. P.S syazskylex

**Comment by androidmads** [comment]
Hi guys,

Try to clear your app's data and import the excel file into the application will works fine.
